### ISSUE TITLE
Regular expressions not working

### ISSUE THREAD

**Issue by MaartenMol** [crate/cratedb-prometheus-adapter#24] opened 2018-11-22 16:02 UTC
When running a query in Grafana with expressions like `name=~"test|123"`, no data is shown. 

I don't know if this is normal or a bug?

**Comment by dominikmoosbrugger** [comment] 2019-01-29 07:44
Hi @MaartenMol, can you please provide more insights for this request? I.e. what CrateDB version and setup, which Prometheus and grafana versions and setup you are using? What is the data you ingest from Prometheus and what is the schema in CrateDB you want to query?

**Comment by amotl** [comment] 2023-01-17 20:11
Dear Maarten,

apologies for replying so late. The whole ecosystem has advanced since you've created this issue, so I am assuming this is not an issue anymore, and it will be safe to close this. Please let me know how to reproduce the error otherwise, and I will be happy to look into it.

With kind regards,
Andreas.

**Comment by amotl** [comment] 2024-01-13 01:06
Dear Maarten,

hi again about this topic, and a happy new year. Even if you might no longer be interested (please tell us), we wanted to tell you that version 0.5.0 has been released today, and we are just now looking at your report again.

On this matter, we can only discover a225ebb28 and GH-27 making changes to the relevant code. By implementing [`prompb.LabelMatcher_RE` and `prompb.LabelMatcher_NRE`](https://github.com/crate/cratedb-prometheus-adapter/blob/0.5.0/server.go#L138-L160), we think regular expressions should work in general.

Maybe it is specific to your expression, which includes the OR operator in form of the pipe symbol `|`?

With kind regards,
Andreas.

**Comment by amotl** [comment] 2024-01-17 00:39
Hi again,

we added corresponding integration tests to verify a few variants of query expressions, and haven't been able to observe any problems so far. 

- GH-115

Thus, I am closing this. Please feel free to re-open if you think the flaw is still there.

With kind regards,
Andreas.

/cc @WalBeh, @SStorm

**Closed by amotl** 2024-01-17 00:39 UTC
